# auto generated from generic/config/options/*
PM2_BUBBLELIB_CFLAGS_KERNEL="$PM2_BUBBLELIB_CFLAGS_KERNEL -finstrument-functions -DPM2_INSTRUMENT"
PM2_BUBBLELIB_MODULE_DEPEND_LIB="${PM2_BUBBLELIB_MODULE_DEPEND_LIB} profile"
