.TH "ma_container_move_per_block"
.SH NOM
ma_container_move_per_block
.SH SYNOPSYS
#include "marcel_allocator.h"
#include "marcel_container.h"

void ma_container_move_per_block(ma_container_t * src_container, ma_container_t* dest_container, int mode)

.SH DESCRIPTION
Cette fonction permet de déplacer un ensemble d'objet d'un réservoir source vers un réservoir destination. 
Elle n'est donc utilisée qu'en politique POLICY_HIERARCHICAL.
La quantité d'objet déplacé n'est calculé qu'à l'intérieur de cette fonction (qui est bloquante).
En effet on commence d'abord par vérouiller les deux réservoirs (source et destination), ensuite on transfère 
min(nb_element de la source, moitié de la capacité restante de la destination) dans le cas de l'allocation(ALLOC_METHOD_PER_BLOCK)
ou min(moitié du nb_element de la source, capacité restante de la destination) dans le cas de la libération(FREE_METHOD_PER_BLOCk).

.SS ARGUMENTS
ma_allocator_t * allocator :
int mode : Ce mode permet de déterminer la quantité d'objet à déplacer.
valeurs possibles : FREE_METHOD_PER_BLOCk ou ALLOC_METHOD_PER_BLOCK. 