#!/bin/sh

# PM2: Parallel Multithreaded Machine
# Copyright (C) 2006 "the PM2 team" (see AUTHORS file)
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

NETWORKS_FILE=networksMadMpi.cfg
MACHINE_FILE=machineMadMpi.cfg

syntax() {
    echo "Syntax: $0 [-f <machine file>] [-net <communication network>]"
    echo "    Default machine file: OAR node file"
    echo "    Default communication network: tcp"
    exit 1
}

NET="tcp"
FILE="$OAR_NODEFILE"

while [ "$1" ] ; do
    if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
	syntax
    elif [ "$1" = "-f" ] ; then
	if [ -z "$2" ] ; then
	    syntax
	    exit 1
	else
	    FILE=$2
	    shift; shift
	fi
    elif [ "$1" == "-net" ] ; then
	if [ -z "$2" ] ; then
	    syntax
	else
	    NET=$2
	    shift; shift
	fi
    else
	syntax
    fi
done

if [ -z "$FILE" ] ; then
    echo "No OAR reservation and no machine file specified"
    exit
elif [ ! -f "$FILE" ] ; then
    echo "Machine file <$FILE> not found"
    exit
fi

# Check the chosen network protocol is enabled
IS_ENABLED=$(pm2-config --protocols | tr ' ' '\012' | grep ^$NET$ 2>/dev/null)
if [ "$NET" != "tcp" ] && [ -z "$IS_ENABLED"] ; then
    echo ""
    echo "*******"
    echo "Warning. The chosen protocol $NET is not enabled in your PM2 flavor"
    echo "*******"
    echo ""
fi

NODES=`(cat $FILE | sort | uniq | tr '\012' ',' | tr ' ' ',' ) | sed 's/,$//'`

(
echo "networks : ({"
echo "    name  : grid5000;"
echo "    hosts : ($NODES);"
echo "    dev   : $NET;"
echo "});"
) > $NETWORKS_FILE

cat $FILE | sort | uniq > $MACHINE_FILE

echo "Generation of $NETWORKS_FILE and $MACHINE_FILE done"
echo "    - nodes:       $NODES"
echo "    - net:         $NET"
echo "You can now start your MPI application:"
echo "   mpirun -config $NETWORKS_FILE -machinefile $MACHINE_FILE -np ..."

