

# PM2: Parallel Multithreaded Machine
# Copyright (C) 2001 "the PM2 team" (see AUTHORS file)
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.


.PHONY: default all
default: all

SRC_DIR	:=	.
BIN_DIR = ../bin/$(PM2_ARCH_SYS)

include ../../Makefile

PM2_APP_CFLAGS	=
PM2_APP_LDFLAGS	=
PM2_APP_LLIBS	=

all:	$(BIN_DIR)/pm2
