BIP_DIR=${BIP_DIR:-/usr/local/bip}
PM2_PROTOCOLS="$PM2_PROTOCOLS mpi"
PM2_LOADER=$PM2_ROOT/mad4/bin/mad4mpi_bip_load
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${BIP_DIR}/include"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${BIP_DIR}/include/mpi"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -L${BIP_DIR}/lib -L${BIP_DIR}/lib/mpi_gnu"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -lmpi -lbip"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DDRV_MPI=mad_MPI"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DEXTERNAL_SPAWN=DRV_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD4_MAD1_MAIN_PROTO=mad_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD4_MAD1_MAIN_PROTO_PARAM=NULL"
