#!/bin/sh

if [ -z "$1" ];
then
	echo "il me faut un nom de programme en argument, ainsi que ses éventuels paramètres"
	exit 1
fi

prog=`basename $1`

shift;

echo "**********************************************"
echo "Cmd: $prog $@"
if [ -x ./$prog-unix ]; then
  echo "************** Unix"
  ./$prog-unix "$@"
fi
if [ -x ./$prog-clone ]; then
  echo "************** Clone"
  ./$prog-clone "$@"
fi
if [ -x ./$prog-linuxthread ] ; then
  echo "************** LinuxThread"
  LD_ASSUME_KERNEL=2.4.5 ./$prog-linuxthread "$@"
fi
if [ -x ./$prog-nptl ] ; then
  echo "************** NPTL"
  ./$prog-nptl "$@"
fi
if [ -x ./$prog-pth ] ; then
  echo "************** GNUPth"
  ./$prog-pth "$@"
fi
echo "************** NGPT"
#LD_LIBRARY_PATH=/home/vdanjean/opt/libc-2.2.5/lib:/home/vdanjean/opt/ngpt-2.2.2/lib /home/vdanjean/opt/libc-2.2.5/lib/ld-linux.so.2 ./$prog-ngpt  "$@"
#echo "************** Marcel-libpthread"
#LD_PRELOAD=/home/vdanjean/build/libpthread/lib/libstackalign.so LD_LIBRARY_PATH=/home/vdanjean/build/libpthread/lib ./$prog-pthread "$@"
echo "************** Marcel-mono"
./$prog-marcel-mono "$@"
echo "************** Marcel-smp"
./$prog-marcel-smp "$@"

echo "************** Marcel-numa"
./$prog-marcel-numa "$@"

