PM2_COMMON_LIBNAME=common
PM2_COMMON_CFLAGS="$PM2_COMMON_CFLAGS -Wall"
PM2_COMMON_CFLAGS="$PM2_COMMON_CFLAGS -fomit-frame-pointer"

if [ "${PM2_ARCH}" = RS6K_ARCH ]; then
  PM2_COMMON_CFLAGS="$PM2_COMMON_CFLAGS -mno-powerpc"
fi

if [ "$PM2_SYS" = WIN32_ARCH -o "$PM2_SYS" = WINNT_SYS -o "$PM2_SYS" = WIN2K_SYS ]; then
  PM2_COMMON_CFLAGS="$PM2_COMMON_CFLAGS -DWIN_SYS"
fi
