PM2_MARCEL_CFLAGS="$PM2_MARCEL_CFLAGS -DMARCEL_SMP -D_REENTRANT"
PM2_MARCEL_LIBS="$PM2_MARCEL_LIBS -lpthread"

if [ "$PM2_SYS" = LINUX_SYS ]; then
    PM2_LD_PRELOAD="${PM2_LD_PRELOAD:+${PM2_LD_PRELOAD}:}$HOME/lib/libpthread.so"
fi
