.TH "ma_container_get"
.SH NOM
ma_container_get
.SH SYNOPSIS
#include "marcel_container.h"

void * ma_container_get(ma_container_t * container) 

.SH DESCRIPTION
Retourne un élement du réservoir si c'est possible (sinon retourne
NULL) et décrémente le nombre d'éléments nb_element du réservoir.
Si la politique est conservative, on ajoute le noeud correspondant à
l'objet retourné à l'allocateur de noeud (à son réservoir associé en fait).

.SS ARGUMENTS
ma_container_t container : le réservoir dans lequel on souhaite obtenir un objet.
