.TH "ma_obj_allocator_init"
.SH NOM
ma_obj_allocator_init
.SH SYNOPSYS
#include "marcel_allocator.h"

void ma_obj_allocator_init(ma_allocator_t * allocator)

.SH DESCRIPTION
Cette fonction permet de créer des réservoirs pour un allocateur, donc selon la politique de cet allocateur on créé un ou des réservoirs.
En politique globale on créé un unique réservoir, en politique locale on créé un réservoir par lwp, en politique hiérarchique on créé également
des réservoirs le long de la hiérarchie mémoire de sorte à former un arbre de réservoir.
Note : dans le cas de la politique hiérarchique, les réservoirs de niveau le plus bas ont pour valeur de max_size celle de l'allocateur, 
ensuite la taille des réservoirs de niveau supérieur est multiplié par CONTAINER_GROWTH_FACTOR : défini dans marcel_allocator.h

.SS ARGUMENTS
ma_allocator_t * allocator : allocateur pour lequel on va créer un ou des réservoirs.