
# NewMadeleine
# Copyright (C) 2006 (see AUTHORS file)
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

SUBDIRS	:= core
SUBDIRS	+= drivers
SUBDIRS	+= protocols
SUBDIRS	+= schedulers

NM_PATH		:= .
MAKE_CONF	:= $(NM_PATH)/make.conf
MAKE_TREE	:= $(NM_PATH)/make.tree

include $(MAKE_CONF)
include $(MAKE_TREE)

