# auto generated from generic/config/options/*
PM2_@LIB@_BUILD_STATIC=yes
PM2_COMMON_PM2_STLIBS="$PM2_COMMON_PM2_STLIBS @LIB@"
PM2_@LIB@_BUILD_DYNAMIC=yes
PM2_COMMON_PM2_SHLIBS="$PM2_COMMON_PM2_SHLIBS @LIB@"
