PM2_PROTOCOLS=pvm
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -I${PVM_ROOT}/include"
PM2_MAD1_LIBS="$PM2_MAD1_LIBS -L${PVM_ROOT}/lib/${PVM_ARCH} -lpvm3"
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DNET_ARCH="'\"'pvm'\"'
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DNETINTERF_INIT=mad_pvm_netinterf_init"
