PM2_PROTOCOLS=via
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DMAD_VIA -D_REENTRANT -DCANT_SEND_TO_SELF -DVIA_DEV_NAME="'\"/dev/via_eth0\"'
PM2_MAD1_LIBS="$PM2_MAD1_LIBS -lvipl -lpthread"
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DNET_ARCH="'\"'via'\"'
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DNETINTERF_INIT=mad_via_netinterf_init"
