PM2_PROTOCOLS="$PM2_PROTOCOLS nmad-tcp"
PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -DCONFIG_TCP"
PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -I${PM2_ROOT}/nmad/drivers/tcp/include"
PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -DDRV_TCP=mad_TCP"

