PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -DCONFIG_PROTO_MAD3"
PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -I${PM2_ROOT}/nmad/protocols/proto_mad3/include"

PM2_NMAD_PROTO="$PM2_NMAD_PROTO proto_mad3"

PM2_NMAD_LAUNCHER="leonie"
