PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -DCONFIG_PROTO_MAD3"
PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -I${PM2_ROOT}/nmad/interfaces/mad3/include"

PM2_NMAD_INTERFACES="$PM2_NMAD_INTERFACES mad3"

PM2_NMAD_LAUNCHER="leonie"
