PM2_NMAD_CFLAGS="$PM2_NMAD_CFLAGS -I$PADICO_ROOT/include -DCONFIG_PADICO -DCONFIG_PUK_PUKABI -DPUK"
PM2_NMAD_LD_PATH="$PM2_NMAD_LD_PATH -L${PADICO_ROOT}/lib -L${PADICO_ROOT}/lib/PukABI"
PM2_NMAD_LIBS="$PM2_NMAD_LIBS -lPadicoPuk -lPukABI"
