# auto generated from generic/config/options/*
PM2_NMAD_BUILD_STATIC=yes
PM2_COMMON_PM2_STLIBS="$PM2_COMMON_PM2_STLIBS NMAD"
PM2_NMAD_BUILD_DYNAMIC=yes
PM2_COMMON_PM2_SHLIBS="$PM2_COMMON_PM2_SHLIBS NMAD"
