# auto generated from generic/config/options/*
PM2_PROFILE_CFLAGS_KERNEL="$PM2_PROFILE_CFLAGS_KERNEL -finstrument-functions -DPM2_INSTRUMENT"
PM2_PROFILE_MODULE_DEPEND_LIB="${PM2_PROFILE_MODULE_DEPEND_LIB} profile"
