PM2_BUBBLELIB_LIBNAME=bubblelib
PM2_BUBBLELIB_LIBS="$PM2_BUBBLELIB_LIBS -lming -lm"
PM2_BUBBLELIB_GENERATE_INCLUDE=true

if [ "$PM2_SYS" = DARWIN_SYS ]; then
    PM2_BUBBLELIB_LIBS="$PM2_BUBBLELIB_LIBS -lfxt"
else
    PM2_BUBBLELIB_LIBS="$PM2_BUBBLELIB_LIBS -lfxt -lbfd -liberty"
fi
