PM2_PROTOCOLS="$PM2_PROTOCOLS mad-madico"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DDRV_MADICO=mad_MADICO"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO=mad_MADICO"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO_PARAM=NULL"
