PM2_PROTOCOLS="$PM2_PROTOCOLS mad-mpi"
PM2_CC=hcc
PM2_LOADER=$PM2_ROOT/mad3/bin/mad3mpi_lam_load
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DDRV_MPI=mad_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO=mad_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO_PARAM=NULL"
