PM2_PROTOCOLS="$PM2_PROTOCOLS mad-rand"
if [ "${PM2_SYS}" = SOLARIS_SYS ]; then
    PM2_MAD3_LIBS="$PM2_MAD3_LIBS -lnsl -lsocket"
fi
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DDRV_RAND=mad_RAND"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO=mad_RAND"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO_PARAM=NULL"
