PM2_PROTOCOLS="$PM2_PROTOCOLS mad-sisci"
#PM2_CC=egcc
#SISCI_PATH=${SISCI_PATH:-${HOME}/DIS/src/SISCI}
SISCI_PATH=${SISCI_PATH:-/opt/DIS}
#PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -I${SISCI_PATH}/api"
#PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -I${SISCI_PATH}/src"
#PM2_MAD3_LD_PATH="$PM2_MAD3_LD_PATH -L${SISCI_PATH}/api"
#PM2_MAD3_LIBS="$PM2_MAD3_LIBS -lsisci"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -I${SISCI_PATH}/include"
PM2_MAD3_LIBS="$PM2_MAD3_LIBS ${SISCI_PATH}/lib/libsisci.a"
#PM2_MAD3_LD_PATH="$PM2_MAD3_LD_PATH -L${SISCI_PATH}/lib"
#PM2_MAD3_LIBS="$PM2_MAD3_LIBS -lsisci"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DDRV_SISCI=mad_SISCI"
#PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -Di686 -fexpensive-optimizations -finline-functions -Dpentiumpro -mcpu=pentiumpro -march=pentiumpro -O6 -fomit-frame-pointer"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO=mad_SISCI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO_PARAM=NULL"
