PM2_PROTOCOLS="$PM2_PROTOCOLS mad-via"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -D_REENTRANT"
PM2_MAD3_LIBS="$PM2_MAD3_LIBS -lvipl -lpthread"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DDRV_VIA=mad_VIA"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO=mad_VIA"
# PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO_PARAM="'\"/dev/via_eth0\"'
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD3_MAD1_MAIN_PROTO_PARAM="'\"/dev/via_lo\"'
