# Additionnal warnings

# Regular warnings
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wall" 

# Extra warnings
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -W" 

# Specific warnings
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wundef" 
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wshadow"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wlarger-than-1024"
# PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wpointer-arith"
# PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wbad-function-cast"
# PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wcast-qual"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wcast-align"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wwrite-strings"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wconversion"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wsign-compare"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Waggregate-return"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wstrict-prototypes"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wmissing-prototypes"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wmissing-declarations"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wmissing-noreturn"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wredundant-decls"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wnested-externs"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Winline"
PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Wlong-long"

# Warnings as error
# PM2_MAD3_CFLAGS_KERNEL="$PM2_MAD3_CFLAGS_KERNEL -Werror"
