MPICH_DIR=${MPICH_DIR:-/opt/mpich}
MPICH_SRC_DIR=${MPICH_SRC_DIR:-/opt/mpich-src}
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DMAD3_PMI"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -I${MPICH_DIR}/include"
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -I${MPICH_SRC_DIR}/src/include"
PM2_MAD3_LIBS="$PM2_MAD3_LIBS -L${MPICH_DIR}/lib -lmpich"
