# auto generated from generic/config/options/*
PM2_MAD3_BUILD_STATIC=yes
PM2_COMMON_PM2_STLIBS="$PM2_COMMON_PM2_STLIBS MAD3"
PM2_MAD3_BUILD_DYNAMIC=yes
PM2_COMMON_PM2_SHLIBS="$PM2_COMMON_PM2_SHLIBS MAD3"
