.TH "ma_container_is_full"
.SH NOM
ma_container_is_full
.SH SYNOPSYS
#include "marcel_container.h"

int ma_container_is_full(ma_container_t * container)

.SH DESCRIPTION
Retourne un entier (en fait un booléen) : 1 si le réservoir est plein, 0 sinon.
Le réservoir est plein lorsque le nombre d'éléments qu'il contient est supérieur ou égal au maximum fixé à sa création.

.SS ARGUMENTS
ma_container_t * container : le réservoir dont on souhaite vérifier s'il est plein.
