# Une (brève) documentation pour savoir comment ajouter un module sans y passer 2 heures.

Pour ajouter un nouveau module, il faut :

- créer un répertoire (par exemple ${PM2_SRCROOT}/plop)
- ajouter un répertoire ${PM2_SRCROOT}/plop/config
- Ajouter le nom du module dans les fichiers suivants : 
	${PM2_SRCROOT}/generic/config/options/Makefile
	${PM2_SRCROOT}/bin/pm2-config.in
- Créer un lien depuis le répertoire ${PM2_SRCROOT}/modules
        cd ${PM2_SRCROOT}/modules ; ln -s ../plop
- puis, on génère les fichiers d'options du module :
	cd ${PM2_SRCROOT}/generic/config/options/ ; make duplique_global
- Finalement, on génère d'autres fichiers dont a besoin pm2.
	cd ${PM2_SRCROOT} ; ./autogen.sh
