.TH "ma_obj_allocator_fini"
.SH NOM
ma_obj_allocator_fini
.SH SYNOPSYS
#include "marcel_allocator.h"

void ma_obj_allocator_fini(ma_allocator_t * allocator)

.SH DESCRIPTION
Cette fonction permet de supprimer tous les réservoirs correspodant à un allocateur.
Si l'option Stat est choisie à la compilation, lors de l'éxécution de cette fonction on affiche le nombre d'éléments dans chaque réservoir.

.SS ARGUMENTS
ma_allocator_t * allocator : allocateur que l'on va supprimer.
