PM2_PROTOCOLS="$PM2_PROTOCOLS sisci"
#PM2_CC=egcc
SISCI_PATH=${SISCI_PATH:-${HOME}/DIS/src/SISCI}
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -I${SISCI_PATH}/api"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -I${SISCI_PATH}/src"
PM2_MAD2_LIBS="$PM2_MAD2_LIBS -L${SISCI_PATH}/api -lsisci"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DDRV_SISCI=mad_SISCI"
#PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -Di686 -fexpensive-optimizations -finline-functions -Dpentiumpro -mcpu=pentiumpro -march=pentiumpro -O6 -fomit-frame-pointer"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO=mad_SISCI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO_PARAM=NULL"
