BIP_DIR=${BIP_DIR:-/usr/local/bip}
PM2_PROTOCOLS="$PM2_PROTOCOLS mpi"
PM2_LOADER=$PM2_ROOT/mad2/bin/mad2mpi_bip_load
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -I${BIP_DIR}/include"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -I${BIP_DIR}/include/mpi"
PM2_MAD2_LIBS="$PM2_MAD2_LIBS -L${BIP_DIR}/lib -L${BIP_DIR}/lib/mpi_gnu"
PM2_MAD2_LIBS="$PM2_MAD2_LIBS -lmpi -lbip"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DDRV_MPI=mad_MPI"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DEXTERNAL_SPAWN=DRV_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO=mad_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO_PARAM=NULL"
