PM2_PROTOCOLS="$PM2_PROTOCOLS tcp"
if [ "${PM2_SYS}" = SOLARIS_SYS ]; then
    PM2_MAD2_LIBS="$PM2_MAD2_LIBS -lnsl -lsocket"
fi
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DDRV_TCP=mad_TCP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO=mad_TCP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO_PARAM=NULL"
