PM2_PROTOCOLS="$PM2_PROTOCOLS via"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -D_REENTRANT"
PM2_MAD2_LIBS="$PM2_MAD2_LIBS -lvipl -lpthread"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DDRV_VIA=mad_VIA"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO=mad_VIA"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO_PARAM="'\"/dev/via_eth0\"'
