BIP_DIR=${BIP_DIR:-/usr/local/bip}
PM2_PROTOCOLS="$PM2_PROTOCOLS bip"
PM2_LOADER=$PM2_ROOT/mad2/bin/mad2bip_load
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -I${BIP_DIR}/include"
PM2_MAD2_LIBS="$PM2_MAD2_LIBS -L${BIP_DIR}/lib"
PM2_MAD2_LIBS="$PM2_MAD2_LIBS -lbip"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DDRV_BIP=mad_BIP"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DEXTERNAL_SPAWN=DRV_BIP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO=mad_BIP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO_PARAM=NULL"
