PM2_PROTOCOLS="$PM2_PROTOCOLS mpi"
PM2_CC=hcc
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DDRV_MPI=mad_MPI"
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DEXTERNAL_SPAWN=DRV_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO=mad_MPI"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD2_MAD1_MAIN_PROTO_PARAM=NULL"
