PM2_MAD4_LIBNAME=mad
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DMAD=4 -DMAD_MINOR=0"
# PM2_DEFAULT_LOADER=$PM2_ROOT/mad4/bin/madload
PM2_MAD4_MODULE_DEPEND_LIB="${PM2_MAD4_MODULE_DEPEND_LIB} tbx ntbx marcel"
