#!/bin/bash
###########

if [ -r build.cfg ]; then
    config=$(cat build.cfg)
fi

export BUILD_CFG=`pwd`/build.cfg

make $config "$@" && (for i in examples/*; do test -d $i && test -r $i/Makefile && (cd $i && make $config "$@"); done)
#
