#!/bin/bash
###########

if [ -r build.cfg ]; then
    config=$(cat build.cfg)
fi

make $config clean && (for i in examples/*; do test -d $i && test -r $i/Makefile && (cd $i && make $config clean); done)
#
