#!/bin/bash
###########

if [ -r build.cfg ]; then
    config=$(cat build.cfg)
fi

export BUILD_CFG=`pwd`/build.cfg
examples="basic mad3 mini sched_opt"

make $config clean && (for j in $examples; do i="examples/$j"; test -d $i && test -r $i/Makefile && (cd $i && make $config clean); done)
#
