	"divide_error",					/*  0 */
	"debug",						/*  1 */
	"nmi",							/*  2 */
	"int3",							/*  3 */
	"overflow",						/*  4 */
	"bounds",						/*  5 */
	"invalid_op",					/*  6 */
	"device_not_available",			/*  7 */
	"double_fault",					/*  8 */
	"coprocessor_seg_overrun",		/*  9 */
	"invalid_TSS",					/* 10 */
	"segment_not_present",			/* 11 */
	"stack_segment",				/* 12 */
	"general_protection",			/* 13 */
	"page_fault",					/* 14 */
	"spurious_interrupt_bug",		/* 15 */
	"coprocessor_error",			/* 16 */
	"alignment_check",				/* 17 */
	"machine_check"					/* 18 */
	"simd_coprocessor_error",		/* 19 */
	"unknown trap",					/* 20 */
