PM2_MAD2_LIBNAME=mad
if [ "${PM2_ARCH}" = RS6K_ARCH ]; then
  PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -mno-powerpc"
fi
PM2_MAD2_CFLAGS="$PM2_MAD2_CFLAGS -DMAD=2 -DMAD_MINOR=1"
PM2_MAD2_MODULE_DEPEND_LIB="${PM2_MAD2_MODULE_DEPEND_LIB} tbx ntbx marcel"
