#!/usr/bin/env python
######################

from optparse import OptionParser
import random
import sys

def cmdline_parse(args):
    """Parse the command line arguments."""
    
    usage = 'usage: %prog [options] FILENAME -- [appli options]'
    version = '%prog 1.0'
    
    parser = OptionParser(usage=usage, version=version)
    parser.add_option('-g', '--gen',  dest='gen', type='string',
                      metavar='GEN',  help='set range generator', default='random')

    parser.add_option('-n', '--nb',    dest='nb',
                          metavar='NB', type='int',
                          help='set number of values', default=1)

    parser.add_option('-m', '--min',    dest='min',
                          metavar='MIN', type='int',
                          help='set minimum value', default=4)
    
    parser.add_option('-M', '--max',    dest='max',
                          metavar='MAX', type='int',
                          help='set maximum value', default=1024*1024)

    parser.add_option('-s', '--step',    dest='step',
                          metavar='STEP', type='int',
                          help='set step value', default=1)

    (options, _args) =  parser.parse_args(args)
    
    if len(_args):
        parser.error('invalid arguments')

    return options

#__________

def gen_random(options):
    list = []
    for i in range(options.nb):
        val = random.randrange(options.min, options.max, options.step)
        list.append(val)
        
    return list
# _ _ _ _ _

def gen_prandom(options):
    list = []
    for i in range(options.nb):
        val_pow	= random.randint(options.min, options.max)
        val	= 1 << val_pow

        while (val_pow):
            val_pow	= val_pow-1
            val		= val | random.randint(0, 1) << val_pow

        list.append(val)
            
    return list
# _ _ _ _ _

def gen_simple(options):
    step = options.step
    if (options.nb > 1):
        step = (options.max - options.min) / (options.nb-1)

    return range(options.min, options.max+1, step)

#__________

gen_dict	= {
    'random': gen_random,
    'prandom': gen_prandom,
    'simple': gen_simple
    }

options	= cmdline_parse(sys.argv[1:])
gen	= gen_dict[options.gen]
list	= gen(options)

list.sort()

for val in list:
    print val

#
