PM2_LEOPARSE_CFLAGS="$PM2_LEOPARSE_CFLAGS -DLEOPARSE_DEBUG"
PM2_LEOPARSE_CFLAGS_KERNEL="$PM2_LEOPARSE_CFLAGS_KERNEL -DDEBUG"
PM2_LEOPARSE_MODULE_DEPEND_LIB="${PM2_LEOPARSE_MODULE_DEPEND_LIB} pm2debug"
