PM2_LEOPARSE_CFLAGS="$PM2_LEOPARSE_CFLAGS -DLEOPARSE_PROFILE"
PM2_LEOPARSE_CFLAGS_KERNEL="$PM2_LEOPARSE_CFLAGS_KERNEL -DDO_PROFILE"
PM2_LEOPARSE_MODULE_DEPEND_LIB="${PM2_LEOPARSE_MODULE_DEPEND_LIB} profile"
