# auto generated from generic/config/options/*
PM2_LEOPARSE_CFLAGS_KERNEL="$PM2_LEOPARSE_CFLAGS_KERNEL -finstrument-functions -DPM2_INSTRUMENT"
PM2_LEOPARSE_MODULE_DEPEND_LIB="${PM2_LEOPARSE_MODULE_DEPEND_LIB} profile"
