# auto generated from generic/config/options/*
PM2_LEOPARSE_BUILD_STATIC=yes
PM2_COMMON_PM2_STLIBS="$PM2_COMMON_PM2_STLIBS LEOPARSE"
PM2_LEOPARSE_BUILD_DYNAMIC=yes
PM2_COMMON_PM2_SHLIBS="$PM2_COMMON_PM2_SHLIBS LEOPARSE"
