
# NewMadeleine
# Copyright (C) 2006 (see AUTHORS file)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

ifeq ($(CONFIG_SCHED_OPT), y)
APP		:= 4-ping big_hello hello mad_micro_sel ping_multirails ping ping_single sr_hello sr_ping sr_ping_any sr_test_any_src dummy latency mad_ping_sel  sr_latency large_small_large_small dsm sr_bench

else
APP		:=
endif

NM_PATH		:= ../..

include $(NM_PATH)/Makefile

#
