PM2_MAD3_LIBNAME=mad3
PM2_MAD3_CFLAGS="$PM2_MAD3_CFLAGS -DMAD=3 -DMAD_MINOR=0"
# PM2_DEFAULT_LOADER=$PM2_ROOT/mad3/bin/madload
PM2_MAD3_MODULE_DEPEND_LIB="${PM2_MAD3_MODULE_DEPEND_LIB} tbx ntbx marcel"
