PM2_MARCEL_FORCE_BUILD_DYNAMIC=yes
PM2_TBX_FORCE_BUILD_DYNAMIC=yes
PM2_MARCEL_MAKEFILE="LIBPTHREAD:=true"
PM2_MARCEL_LIBNAME=pthread
PM2_MARCEL_CFLAGS="$PM2_MARCEL_CFLAGS -DMARCEL_LIBPTHREAD"
PM2_MARCEL_LIBS="$PM2_MARCEL_LIBS -lPukABI -lrt"
# make libpthread be linked against all other libs, so as to pull them
# automatically at runtime.
PM2_MARCEL_LINK_OTHERS=yes

PM2_LD_PRELOAD="${PM2_LD_PRELOAD:+${PM2_LD_PRELOAD}:}libpthread.so"
