# auto generated from generic/config/options/*
PM2_PM2_BUILD_STATIC=yes
PM2_COMMON_PM2_STLIBS="$PM2_COMMON_PM2_STLIBS PM2"
PM2_PM2_BUILD_DYNAMIC=yes
PM2_COMMON_PM2_SHLIBS="$PM2_COMMON_PM2_SHLIBS PM2"
