PM2_PROTOCOLS=shm
PM2_LOADER=${PM2_ROOT}/mad1/bin/tcp/madload
PM2_MAD1_LIBS="$PM2_MAD1_LIBS -lposix4"
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DNET_ARCH="'\"'shm'\"'
PM2_MAD1_CFLAGS="$PM2_MAD1_CFLAGS -DNETINTERF_INIT=mad_shm_netinterf_init"
