#!/bin/bash
###########

if [ $# -eq 0 ]; then
	GCC_DIR="gcc-4.2.2"
elif [ $# -eq 1 ]; then
	GCC_DIR="$1"
else
	GCC_ORIG_DIR="$1"
	GCC_DIR="$2"
fi

if [ -z "${GCC_ORIG_DIR}" ]; then
	GCC_ORIG_DIR="${GCC_DIR}.orig"
fi

diff -uprN -X diff_exclude -x libgomp ${GCC_ORIG_DIR} ${GCC_DIR} > forestgomp_gcc.patch
diff -uprN -X diff_exclude  ${GCC_ORIG_DIR}/libgomp ${GCC_DIR}/libgomp > forestgomp_libgomp.patch

#

