PM2_MAD4_LIBNAME=mad
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DMAD=4 -DMAD_MINOR=0"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${PM2_ROOT}/mad4/include/core"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${PM2_ROOT}/mad4/include/mad3"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${PM2_ROOT}/mad4/include/services"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${PM2_ROOT}/mad4/include/network"
# PM2_DEFAULT_LOADER=$PM2_ROOT/mad4/bin/madload
PM2_MAD3_MODULE_DEPEND_LIB="${PM2_MAD4_MODULE_DEPEND_LIB} tbx ntbx marcel"
