# auto generated from generic/config/options/*
PM2_SIGMUNDLIB_CFLAGS_KERNEL="$PM2_SIGMUNDLIB_CFLAGS_KERNEL -finstrument-functions"
PM2_SIGMUNDLIB_MODULE_DEPEND_LIB="${PM2_SIGMUNDLIB_MODULE_DEPEND_LIB} profile"
