# auto generated from generic/config/options/*
PM2_SIGMUNDLIB_CFLAGS_KERNEL="$PM2_SIGMUNDLIB_CFLAGS_KERNEL -DDO_PROFILE"
PM2_SIGMUNDLIB_MODULE_DEPEND_LIB="${PM2_SIGMUNDLIB_MODULE_DEPEND_LIB} profile"
