BIP_DIR=${BIP_DIR:-/usr/local/bip}
PM2_PROTOCOLS="$PM2_PROTOCOLS bip"
PM2_LOADER=$PM2_ROOT/mad4/bin/mad4bip_load
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${BIP_DIR}/include"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -L${BIP_DIR}/lib"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -lbip"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DDRV_BIP=mad_BIP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD4_MAD1_MAIN_PROTO=mad_BIP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD4_MAD1_MAIN_PROTO_PARAM=NULL"
