IB_ROOT=${IB_ROOT:-/usr}
PM2_PROTOCOLS="$PM2_PROTOCOLS ibverbs"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DCONFIG_IBVERBS"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${PM2_ROOT}/nmad/drivers/ibverbs/include -I${IB_ROOT}/include"
PM2_MAD4_LD_PATH="$PM2_MAD4_LD_PATH -L${IB_ROOT}/lib"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -libverbs"

