PM2_PROTOCOLS="$PM2_PROTOCOLS sisci"
SISCI_PATH=${SISCI_PATH:-/opt/DIS}
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DCONFIG_SISCI"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${SISCI_PATH}/include"
PM2_MAD4_LD_PATH="$PM2_MAD4_LD_PATH -L${SISCI_PATH}/lib"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -lsisci"
