PM2_PROTOCOLS="$PM2_PROTOCOLS vrp"
if [ "${PM2_SYS}" = SOLARIS_SYS ]; then
    PM2_MAD4_LIBS="$PM2_MAD4_LIBS -lnsl -lsocket"
fi
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DDRV_VRP=mad_VRP -I${VRP_ROOT}"
PM2_MAD4_LD_PATH="$PM2_MAD4_LD_PATH -L${VRP_ROOT}"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -lvrp"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD4_MAD1_MAIN_PROTO=mad_VRP"
PM2_PM2_CFLAGS="$PM2_PM2_CFLAGS -DMAD4_MAD1_MAIN_PROTO_PARAM=NULL"
