PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -DCONFIG_PROTO_MPI"
PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I${PM2_ROOT}/nmad/protocols/proto_mpi/include"

PM2_NMAD_PROTO="$PM2_NMAD_PROTO proto_mpi"

PM2_NMAD_LAUNCHER="leonie"

