PM2_MAD4_CFLAGS="$PM2_MAD4_CFLAGS -I$PADICO_ROOT/include -DCONFIG_PADICO"
PM2_MAD4_LD_PATH="$PM2_MAD4_LD_PATH -L$PADICO_ROOT/lib"
PM2_MAD4_LIBS="$PM2_MAD4_LIBS -L$PADICO_ROOT/lib -lexpat -ldl -lPadicoPuk"
