
#ifndef DSM_RPC_IS_DEF
#define DSM_RPC_IS_DEF

#include "dsm_const.h"
#include "dsm_mutex.h"


BEGIN_LRPC_LIST
  DSM_LRPC_READ_PAGE_REQ,
  DSM_LRPC_WRITE_PAGE_REQ,
  DSM_LRPC_SEND_PAGE,
  DSM_LRPC_INVALIDATE_REQ,
  DSM_LRPC_INVALIDATE_ACK,
  DSM_LRPC_SEND_DIFFS,
  DSM_LRPC_LOCK,
  DSM_LRPC_UNLOCK,
  DSM_LRPC_MULTIPLE_READ_PAGE_REQ,
  DSM_LRPC_MULTIPLE_WRITE_PAGE_REQ,
  DSM_LRPC_SEND_MULTIPLE_PAGES_READ,
  DSM_LRPC_SEND_MULTIPLE_PAGES_WRITE,
  DSM_LRPC_SEND_MULTIPLE_DIFFS,
  DSM_LRPC_HBRC_DIFFS
END_LRPC_LIST


void dsm_pm2_init_rpc(void);

#endif


